### PR TITLE
Use const modifier when possible

### PR DESCRIPTION
**Pull request by f2404**
plus some spelling fixes;
don't use typecast for malloc() in C.

### CODE REVIEW

**Comment by dmitrii-eremin** [comment]
I agree about const modifiers. But I disagree that isn't necessary to use typecasts for `malloc()` in C. What if JFES will be compiling with C++ compiler? Yes, I know that every object file is necessary to compile their compiler. But С++ compiler is almost 100% compatible with C. 
I don't want to see warnings in C++.

**Comment by f2404** [comment]
Ok, understood.
Let me update this PR to restore typecasts.

**Comment by f2404** [comment]
Typecasts restored.

**Comment by dmitrii-eremin** [comment]
Thank you for this PR.

**Pull request merged**
